version: '3.3'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.5
    ports:
      # The HTTP port
      - "80:80"
      # The HTTP port
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "9999:8080"
    env_file: .env
    restart: 'unless-stopped'
    networks:
      - traefik
    volumes:
      # So that Traefik can listen to the Docker events
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./acme.json:/acme.json
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./log-file.log:/log-file.log
      - ./log-access.log:/log-access.log

networks:
  traefik:
    driver: bridge
    external: true
